# Generated by Django 4.0.5 on 2022-07-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RgisterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('Candidate', 'Candidate'), ('Interviewer', 'Interviewer')], max_length=25)),
                ('avail_from', models.CharField(choices=[('1', '1 am'), ('2', '2 am'), ('3', '3 am'), ('4', '4 am'), ('5', '5 am'), ('6', '6 am'), ('7', '7 am'), ('8', '8 am'), ('9', '9 am'), ('10', '10 am'), ('11', '11 am'), ('12', '12 am'), ('13', '1 am'), ('14', '2 am'), ('15', '3 am'), ('16', '4 am'), ('17', '5 am'), ('18', '6 am'), ('19', '7 am'), ('20', '8 am'), ('21', '9 am'), ('22', '10 am'), ('23', '11 am'), ('24', '12 am')], max_length=25)),
                ('avail_to', models.CharField(choices=[('1', '1 am'), ('2', '2 am'), ('3', '3 am'), ('4', '4 am'), ('5', '5 am'), ('6', '6 am'), ('7', '7 am'), ('8', '8 am'), ('9', '9 am'), ('10', '10 am'), ('11', '11 am'), ('12', '12 am'), ('13', '1 am'), ('14', '2 am'), ('15', '3 am'), ('16', '4 am'), ('17', '5 am'), ('18', '6 am'), ('19', '7 am'), ('20', '8 am'), ('21', '9 am'), ('22', '10 am'), ('23', '11 am'), ('24', '12 am')], max_length=25)),
            ],
        ),
    ]
