# Generated by Django 4.0.5 on 2022-07-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RgisterClass',
            new_name='RegisterModel',
        ),
    ]
